apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CN_BASE}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CN_BASE}
  template:
    metadata:
      labels:
        app: ${CN_BASE}
    spec:
      containers:
        - name: ${CN_BASE}
          image: TODO!!!
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "0.05"
              memory: 1024Mi
          ports:
          - containerPort: 8443
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls"
              readOnly: true          
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-certs