kind: Service
apiVersion: v1
metadata:
  name: ${CN_BASE}
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: ${CN_BASE}
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster
