apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: yalos
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlES2pDQ0FoS2dBd0lCQWdJVUU0Z2gxTFhpZEdUdWlxWUluZ1dNRWR0bzVBUXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3RnpFVk1CTUdBMVVFQXd3TVlXUnRhWE56YVc5dVgyTmhNQ0FYRFRJek1ETXlOekUyTkRVME1sb1lEekl5DQpPVGN3TVRBNU1UWTBOVFF5V2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHDQpTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEcXFZTVVCN290bjBmYnc5ajdqMEJMcmo4d3BOdEozd0lUDQowa2VzWTBlWnl3cEwxaWowSXR4elRQcU44Q21qMHdLOTFXZWJTdWE3VXJvd1Q4TDR3R0pRMFpZa25NdTkrend2DQpVeTBkdWxKblRWWGVIb3V1ZmU4aEtUVVc1Y0hCSnpRRW9tNkQxV0hHRzJDSlUzNTFKMGpVQVoxZ3k4TE1ybVRGDQprS3FkOFJUSjU4K2NETXByRStnSXJadURzSHphaytpVVBDRHJkNFdaTjNPWGowWUVueVhDcFpXWGN2SE9LTGU0DQpuZ01XVldUNFpHdnU3R3YwZytqNzlYd1lZV3BnRmxiL3gweDQvbmUxZGRCMDJJV0IyVnA0eHZPVVdnc3pLTXZRDQorVEx6SVJlYVJGSlJBUy9VOE5rMmtNUGUxSVBjK2taZDVJTWQ4SHFHdjhzb3pramNaOVByQWdNQkFBR2piREJxDQpNQjBHQTFVZERnUVdCQlRYTVkvS21Eb1E3ZEswNXU2SllEWlR2OW1COGpBZkJnTlZIU01FR0RBV2dCVFhNWS9LDQptRG9RN2RLMDV1NkpZRFpUdjltQjhqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CY0dBMVVkRVFRUU1BNkNER0ZrDQpiV2x6YzJsdmJsOWpZVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBMWxQckJNUGxxSHR5OWFPQWdHMllMdC8zDQpOQlp2YWtZdlNBUitEZjEvVjVPSmV0VUxDVFV0SElrVURLV29EL1M2OUVhQit1S1ZZemJxVm5xMkNJK0diejBDDQpJMWlYSDluSXAwS3JwalZJZFpkOWFmVWhTUFVXdm4rdlo2SHZiT0NuRHJ4Q2VQZ3cwNExONU1aNGtqWTQ0WURpDQpjWjcrQ3JsclVpZ016U1JqaTZ4SGM3bVZTWXNFSUx0ZjQ1dmladUhhUHhaVXlBVFl6eGhUOFBod3FMUkVXL2JsDQp4bkxVMkFxMldJTXdZK1l0TGhUYUd4VDBPSUpkT2dIQ2pnZytQSmR3Nk9EbmlxRm9JQk01Z0xuQWVaaVp6aDZ6DQpaUm9YUjg3MVlIMkJPUDBiR2pQQUlLNjZmZml6R0hRS3pUVDZISHZ2UzhIQ2ozblNpczhjcm5lTjRqYWNVUT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
    service:
      name: admission
      namespace: yalos
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: yalos.k8s.io
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  sideEffects: None
  timeoutSeconds: 30
